ORGANIZATION_BLOCK "MOD_ERR"
TITLE = "Module Access Error"
{ S7_Optimized_Access := 'FALSE' }
VERSION : 0.1
   VAR_TEMP 
      OB122_EV_CLASS : Byte;   // 16#29, Event class 2, Entering event state, Internal fault event
      OB122_SW_FLT : Byte;   // 16#XX Software error code
      OB122_PRIORITY : Byte;   // Priority of OB Execution
      OB122_OB_NUMBR : Byte;   // 122 (Organization block 122, OB122)
      OB122_BLK_TYPE : Byte;   // 16#88/8C/8E Type of block fault occured in
      OB122_MEM_AREA : Byte;   // Memory area where access error occured
      OB122_MEM_ADDR : Word;   // Memory address where access error occured
      OB122_BLK_NUM : Word;   // Block number in which error occured
      OB122_PRG_ADDR : Word;   // Program address where error occured
      OB122_DATE_TIME : Date_And_Time;   // Date and time OB1 started
   END_VAR


BEGIN
END_ORGANIZATION_BLOCK

